language: smalltalk
sudo: true

os:
  - linux
  - osx

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0

before_install:
  - |
    case $TRAVIS_OS_NAME in
    linux)
      git clone --depth 1 --branch v1.1.0 https://github.com/bats-core/bats-core.git
      export PATH="$(pwd)/bats-core/bin:$PATH"
      ;;
    osx)
      brew install bats-core
      ;;
    esac

script:
  - smalltalkci
  - bats tests
